# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171tMZV6OYkxuOIwYwpA5uQrG6wjrArqw
"""

a=[1,4,8,9]
b=a.copy()
print(b)