# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171tMZV6OYkxuOIwYwpA5uQrG6wjrArqw
"""

list=[6,7,8,5,4,32,8,6,908,675]
total=sum(list)
print(total)

