# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171tMZV6OYkxuOIwYwpA5uQrG6wjrArqw
"""

list=[]
if(len(list)==0):
  print("list is not present")
else:
  print("list is present")

