# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171tMZV6OYkxuOIwYwpA5uQrG6wjrArqw
"""

#largest and smallest numbers from list
list=[4,42,8,6,9,3]
print(max(list))
print(min(list))

